#######################################################
# 
# Pickle.py
# Python implementation of the Class Pickle
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO

class Pickle:
    m_DAO= DAO()
