#######################################################
# 
# Aporte.py
# Python implementation of the Class Aporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from entidades.Fluxo import Fluxo

class Aporte(Fluxo):
    def __init__(self, ident:int, obs: str, valor: int, data: str):
        super().__init__(ident, obs, valor, data)
        