#######################################################
# 
# Aporte.py
# Python implementation of the Class Aporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from entidades.Fluxo import Fluxo

class Aporte(Fluxo):
    pass