#######################################################
# 
# Caixa.py
# Python implementation of the Class Caixa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################


class Caixa:
    __valor_atual = 0