#######################################################
# 
# Contador.py
# Python implementation of the Class Contador
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################


class Contador:
    pass