#######################################################
# 
# ContadorPlataforma.py
# Python implementation of the Class ContadorPlataforma
# Generated by Enterprise Architect
# Created on:      16-Apr-2024 3:14:54 AM
# Original author: rlnet
# 
#######################################################
from entidades.Contador import Contador

class ContadorPlataforma(Contador):

    def __init__(self):
        self.__valor = 500000

    @property
    def valor(self):
        return self.__valor

    @valor.setter
    def valor(self, valor):
        self.__valor = valor