#######################################################
# 
# ContadorSaque.py
# Python implementation of the Class ContadorSaque
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from entidades.Contador import Contador

class ContadorSaque(Contador):
    pass