#######################################################
# 
# Despesa.py
# Python implementation of the Class Despesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from datetime import date
from entidades.Imovel import Imovel
from entidades.Fluxo import Fluxo

class Despesa(Fluxo):
    def __init__(self, ident: int, obs: str, valor: float, data: str, imovel: Imovel, tags: list[str]):
        super().__init__(ident, obs, valor, data)
        self.__imovel = imovel
        self.__tags = tags

    @property
    def imovel(self) -> Imovel:
        return self.__imovel

    @imovel.setter
    def imovel(self, imovel:Imovel):
        self.__imovel = imovel

    @property
    def tags(self) -> list[str]:
        return self.__tags

    @tags.setter
    def tags(self, tags: list[str]):
        self.__tags = tags

    # def __repr__(self):
    #     return f"Data: {self.data} - Valor: {self.valor} - Observação: {self.obs} - Id: {self.id} - Imóvel: {self.imovel}"