#######################################################
# 
# Despesa.py
# Python implementation of the Class Despesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from entidades.Imovel import Imovel
from entidades.Fluxo import Fluxo

class Despesa(Fluxo):
    pass