#######################################################
# 
# Receita.py
# Python implementation of the Class Receita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from entidades.Imovel import Imovel
from entidades.Plataforma import Plataforma
from entidades.Fluxo import Fluxo

class Receita(Fluxo):

    def __init__(self, ident: int, obs: str, valor: float, data: str, imovel: Imovel, plataforma: Plataforma, tags: list[str]):
        super().__init__(ident, obs, valor, data)
        self.__imovel = imovel
        self.__plataforma = plataforma
        self.__tags = tags

    @property
    def imovel(self) -> Imovel:
        return self.__imovel

    @imovel.setter
    def imovel(self, imovel:Imovel):
        self.__imovel = imovel

    @property
    def plataforma(self) -> Plataforma:
        return self.__plataforma

    @plataforma.setter
    def plataforma(self, plataforma:Plataforma):
        self.__plataforma = plataforma

    @property
    def tags(self) -> list[str]:
        return self.__tags

    @tags.setter
    def tags(self, tags: list[str]):
        self.__tags = tags
