#######################################################
# 
# Receita.py
# Python implementation of the Class Receita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from entidades.Imovel import Imovel
from entidades.Plataforma import Plataforma
from entidades.Fluxo import Fluxo

class Receita(Fluxo):
    pass