#######################################################
# 
# DAO.py
# Python implementation of the Class DAO
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from abc import ABC, abstractmethod
class DAO(ABC):

    @abstractmethod
    def __init__(self):
        pass


    @abstractmethod
    def read(self):
        pass

