#######################################################
# 
# DAOAporte.py
# Python implementation of the Class DAOAporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.Aporte import Aporte

class DAOAporte(DAO):
    def __init__(self, arquivo: str):
        self.__arquivo = arquivo
        if os.path.exists(self.__arquivo):
            self.__conteudo = pickle.load(open(self.__arquivo, "rb"))
        else:
            self.__conteudo = []

    @property
    def conteudo(self):
        return self.__conteudo


    def create(self):
        pass

    def delete(self):
        pass

    def read(self):
        pass