#######################################################
# 
# DAOAporte.py
# Python implementation of the Class DAOAporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Aporte import Aporte

class DAOAporte(DAO):
    m_Aporte= Aporte()

    def create():
        pass

    def delete():
        pass

    def read():
        pass