#######################################################
# 
# DAOContadorReceita.py
# Python implementation of the Class DAOContadorReceita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.ContadorReceita import ContadorReceita

class DAOContadorReceita(DAO):
    def __init__(self):
        super().__init__("contadorReceita.pkl")

    def create(self):
        pass

    def read(self):
        pass

    def update(self):
        pass