#######################################################
# 
# DAOContadorAporte.py
# Python implementation of the Class DAOContadorAporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.ContadorAporte import ContadorAporte

class DAOContadorAporte(DAO):
    def __init__(self):
        super().__init__("contadorAporte.pkl")

    def create(self):
        pass

    def read(self):
        pass

    def update(self):
        pass