#######################################################
# 
# DAOCaixa.py
# Python implementation of the Class DAOCaixa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from entidades.Caixa import Caixa
from DAOs.DAO import DAO

class DAOCaixa(DAO):
    m_Caixa= Caixa()

    def create(self):
        pass

    def delete(self):
        pass

    def read(self):
        pass

    def update(self):
        pass