#######################################################
# 
# DAOContadorSaque.py
# Python implementation of the Class DAOContadorSaque
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.ContadorSaque import ContadorSaque

class DAOContadorSaque(DAO):
    def __init__(self):
        pass

    def create(self):
        pass

    def read(self):
        pass

    def update(self):
        pass