#######################################################
# 
# DAOContadorSaque.py
# Python implementation of the Class DAOContadorSaque
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.ContadorSaque import ContadorSaque

class DAOContadorSaque(DAO):
    m_ContadorSaque= ContadorSaque()

    def create():
        pass

    def read():
        pass

    def update():
        pass