#######################################################
# 
# DAOContadorDespesa.py
# Python implementation of the Class DAOContadorDespesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.ContadorDespesa import ContadorDespesa

class DAOContadorDespesa(DAO):
    m_ContadorDespesa= ContadorDespesa()

    def create():
        pass

    def read():
        pass

    def update():
        pass