#######################################################
# 
# DAOContadorAporte.py
# Python implementation of the Class DAOContadorAporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.ContadorAporte import ContadorAporte

class DAOContadorAporte(DAO):
    m_ContadorAporte= ContadorAporte()

    def create():
        pass

    def read():
        pass

    def update():
        pass