#######################################################
# 
# DAOContadorImovel.py
# Python implementation of the Class DAOContadorImovel
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.ContadorImovel import ContadorImovel

class DAOContadorImovel(DAO):
    m_ContadorImovel= ContadorImovel()

    def create():
        pass

    def read():
        pass

    def update():
        pass