#######################################################
# 
# DAOContadorPlataforma.py
# Python implementation of the Class DAOContadorPlataforma
# Generated by Enterprise Architect
# Created on:      16-Apr-2024 3:14:54 AM
# Original author: rlnet
# 
#######################################################
from entidades.ContadorPlataforma import ContadorPlataforma
from DAOs.DAO import DAO

class DAOContadorPlataforma(DAO):
    def __init__(self):
        pass

    def read(self):
        pass

    def update(self):
        pass