#######################################################
# 
# DAOContadorDespesa.py
# Python implementation of the Class DAOContadorDespesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.ContadorDespesa import ContadorDespesa

class DAOContadorDespesa(DAO):
    def __init__(self):
        super().__init__("contadorDespesa.pkl")

    def create(self):
        pass

    def read(self):
        pass

    def update(self):
        pass