#######################################################
# 
# DAOContadorReceita.py
# Python implementation of the Class DAOContadorReceita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.ContadorReceita import ContadorReceita

class DAOContadorReceita(DAO):
    class DAOContadorReceita(DAO):
        def __init__(self, arquivo: str):
            self.__arquivo = arquivo
            self._DAOContadorReceita__conteudo = []
            try:
                self._DAOContadorReceita__conteudo = self.__load()
            except FileNotFoundError:
                self.__dump()
                self.__load()

        def read(self) -> int:
            pass

        def update(self):
            pass

        def __dump(self):
            with open(self.__arquivo, 'wb') as arquivo:
                pickle.dump(self.conteudo, arquivo)

        def __load(self):
            with open(self.__arquivo, 'rb') as arquivo:
                self.conteudo = pickle.load(arquivo)
            return self.conteudo