#######################################################
# 
# DAOContadorReceita.py
# Python implementation of the Class DAOContadorReceita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.ContadorReceita import ContadorReceita

class DAOContadorReceita(DAO):
    m_ContadorReceita= ContadorReceita()

    def create(self):
        pass

    def read(self):
        pass

    def update(self):
        pass