#######################################################
# 
# DAOContadorImovel.py
# Python implementation of the Class DAOContadorImovel
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.ContadorImovel import ContadorImovel

class DAOContadorImovel(DAO):

    def __init__(self):
        super().__init__("contadorImovel.pkl")


    def create(self):
        pass

    def read(self):
        pass

    def update(self):
        pass