#######################################################
# 
# DAODespesa.py
# Python implementation of the Class DAODespesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Despesa import Despesa

class DAODespesa(DAO):
    m_Despesa= Despesa()

    def create():
        pass

    def delete():
        pass

    def read():
        pass