#######################################################
# 
# DAOImovel.py
# Python implementation of the Class DAOImovel
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Imovel import Imovel

class DAOImovel(DAO):
    m_Imovel= Imovel()

    def create(self):
        pass

    def delete(self):
        pass

    def read(self):
        pass

    def update(self):
        pass