#######################################################
# 
# DAOPlataforma.py
# Python implementation of the Class DAOPlataforma
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Plataforma import Plataforma

class DAOPlataforma(DAO):
    m_Plataforma= Plataforma()

    def create(self):
        pass

    def delete(self):
        pass

    def read(self):
        pass

    def update(self):
        pass