#######################################################
# 
# DAOReceita.py
# Python implementation of the Class DAOReceita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Receita import Receita

class DAOReceita(DAO):
    m_Receita= Receita()

    def create(self):
        pass

    def delete(self):
        pass

    def read(self):
        pass