#######################################################
# 
# DAOSenha.py
# Python implementation of the Class DAOSenha
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.Senha import Senha

class DAOSenha(DAO):
    def __init__(self, arquivo: str):
        self.__arquivo = arquivo
        if os.path.exists(self.__arquivo):
            self.__conteudo = pickle.load(open(self.__arquivo, "rb"))
        else:
            self.__conteudo = ["abc123"]
            pickle.dump(self.__conteudo, open(self.__arquivo, "wb"))

    @property
    def conteudo(self) -> list:
        return self.__conteudo
    def read(self) -> str:
        return self.conteudo[0]

    def update(self, nova_senha: str) -> bool:
        self.conteudo[0] = nova_senha
        pickle.dump(self.__conteudo, open(self.__arquivo, "wb"))
        if self.conteudo[0] == nova_senha:
            return True
        else:
            return False