#######################################################
# 
# DAOSenha.py
# Python implementation of the Class DAOSenha
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Senha import Senha

class DAOSenha(DAO):
    m_Senha= Senha()

    def create():
        pass

    def read():
        pass

    def update():
        pass