#######################################################
# 
# DAOSaque.py
# Python implementation of the Class DAOSaque
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAO import DAO
from entidades.Saque import Saque

class DAOSaque(DAO):
    m_Saque= Saque()

    def create():
        pass

    def delete():
        pass

    def read():
        pass