#######################################################
# 
# DAOSaque.py
# Python implementation of the Class DAOSaque
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
import os, pickle
from DAOs.DAO import DAO
from entidades.Saque import Saque

class DAOSaque(DAO):
    def __init__(self):
        super().__init__("saque.pkl")
        self.__schema = Saque()

    def create(self):
        pass

    def delete(self):
        pass

    def read(self):
        pass