#######################################################
# 
# TelaPopup.py
# Python implementation of the Class TelaPopup
# Generated by Enterprise Architect
# Created on:      16-Apr-2024 7:12:15 AM
# Original author: rlnet
# 
#######################################################
import PySimpleGUI as sg
from limites.Tela import Tela

class TelaPopup(Tela):

    def __init__(self):
        self.__window = None

    def mostra_popup(self, mensagem):
        sg.popup(mensagem)