#######################################################
# 
# TelaExcluiImoveis.py
# Python implementation of the Class TelaExcluiImoveis
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg

class TelaExcluiImoveis(Tela):

    def __init__(self):
        self.__window = None

    def excluir_imovel(self, imoveis):
        sg.theme('TealMono')
        layout = [
            [sg.Text('Excluir Imóvel')],
            [sg.Listbox(values=imoveis, size=(100,6))],
            [sg.Button('Excluir'), sg.Button('Cancelar')]
        ]
        self.__window = sg.Window('Excluir Imóvel').Layout(layout)
        button, values = self.__window.Read()
        self.close()
        if button == 'Excluir':
            print(values[0][0].id)
            return values[0][0].id
        else:
            return None


    def close(self):
        self.__window.Close()
        self.__window = None