#######################################################
# 
# TelaExcluiImoveis.py
# Python implementation of the Class TelaExcluiImoveis
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg

class TelaExcluiImoveis(Tela):

    def __init__(self):
        self.__window = None

    # def excluir_imovel(self, imoveis):
    #     sg.theme('Reddit')
    #     layout = [
    #         [sg.Text('Excluir Imóvel')],
    #         [sg.Listbox(values=imoveis, size=(100,6))],
    #         [sg.Button('Excluir'), sg.Button('Cancelar')]
    #     ]
    #     self.__window = sg.Window('Excluir Imóvel').Layout(layout)
    #     button, values = self.__window.Read()
    #     self.close()
    #     if button == 'Excluir':
    #         return values[0][0].id
    #     else:
    #         return None

    def excluir_imovel(self, imoveis):
        sg.theme('Reddit')

        dados = [[imovel.titulo, imovel.desc, imovel.id] for imovel in imoveis]

        colunas = ['Título', 'Descrição', 'ID']

        layout = [
            [sg.Text('Lista Imóveis:', font=("Helvetica", 20), pad=(30, 20))],
            [sg.Table(values=dados, headings=colunas, display_row_numbers=False,
                      auto_size_columns=False, num_rows=min(25, len(dados)), pad=(30, 30), col_widths=[15, 30, 5])],
            [sg.Text('Digite o ID do imóvel que deseja excluir:',font=("Helvetica", 15), pad=(30, 20))],
            [[sg.Text('ID:',font=("Helvetica", 15), pad=(30, 20)), sg.Input(key='id', pad=(30, 20))]],
            [sg.Button('Voltar', pad=(30, 30), button_color=('white', 'red')), sg.Button('Excluir', pad=(0, 30))]
        ]

        self.__window = sg.Window('RBR Imóveis').Layout(layout)
        button, values = self.__window.Read()
        if button is None or button == 'Voltar':
            self.__window.Close()
            return None
        self.__window.Close()
        return values['id']


    def close(self):
        self.__window.Close()
        self.__window = None