#######################################################
# 
# TelaPlataformas.py
# Python implementation of the Class TelaPlataformas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
import PySimpleGUI as sg

class TelaPlataformas:

    C_PLATAFORMAS = "C_PLATAFORMAS"
    R_PLATAFORMAS = "R_PLATAFORMAS"
    U_PLATAFORMAS = "U_PLATAFORMAS"
    D_PLATAFORMAS = "D_PLATAFORMAS"
    def __init__(self):
        self.__window = None

    def abrir_menu(self):
        sg.theme('Reddit')
        layout = [
            [sg.Radio('Cadastrar Plataforma', group_id="plataformas" , key='C_PLATAFORMAS')],
            [sg.Radio('Listar Plataformas', group_id="plataformas", key='R_PLATAFORMAS')],
            [sg.Radio('Alterar Plataforma', group_id="plataformas", key='U_PLATAFORMAS')],
            [sg.Radio('Excluir Plataforma', group_id="plataformas", key='D_PLATAFORMAS')],
            [sg.Button('Prosseguir' , key='PROXIMO')],
            [sg.Button('Retornar', key='VOLTAR')]
        ]
        self.__window = sg.Window('Menu Plataformas').Layout(layout)
        button, values = self.__window.Read()
        if button == 'VOLTAR':
            self.__window.Close()
            return None
        else:
            for key in values:
                if values[key]:
                    escolha = key
                    self.__window.Close()
                    return escolha
            self.__window.Close()
            return None
