#######################################################
# 
# Tela.py
# Python implementation of the Class Tela
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################

from abc import ABC, abstractmethod
import PySimpleGUI as sg
class Tela(ABC):
    IMOVEIS = "IMOVEIS"
    PLATAFORMAS = "PLATAFORMAS"
    DESPESAS = "DESPESAS"
    RECEITAS = "RECEITAS"
    U_SENHA = "U_SENHA"
    C_DESPESAS = "C_DESPESAS"
    R_DESPESAS = "R_DESPESAS"
    D_DESPESAS = "D_DESPESAS"
    C_RECEITAS = "C_RECEITAS"
    R_RECEITAS = "R_RECEITAS"
    D_RECEITAS = "D_RECEITAS"
    C_PLATAFORMAS = "C_PLATAFORMAS"
    R_PLATAFORMAS = "R_PLATAFORMAS"
    U_PLATAFORMAS = "U_PLATAFORMAS"
    D_PLATAFORMAS = "D_PLATAFORMAS"
    PROSSEGUIR = "PROSSEGUIR"
    ROXIMO = "PROXIMO"
    VOLTAR = "VOLTAR"
    SAIR = "SAIR"
    def __init__(self):
        self.__window = None

    def mostra_popup(self, mensagem):
        sg.popup(mensagem, title="ERRO")

    def close(self):
        self.__window.Close()
        self.__window = None
