#######################################################
# 
# TelaCadastraImoveis.py
# Python implementation of the Class TelaCadastraImoveis
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg


class TelaCadastraImoveis(Tela):
    PROSSEGUIR = "PROSSEGUIR"
    VOLTAR = "VOLTAR"

    def __init__(self):
        self.__window = None

    def cadastrar_imovel(self):
        sg.theme('Reddit')

        column1 = [[sg.Text('Titulo:', font=("Helvetica", 15), ), sg.Input(key='titulo', pad=(45, 0) )],
                   [sg.Text('Descrição:', font=("Helvetica", 15), ), sg.Input(key='descricao', )]]
        layout = [
            [sg.Column([[sg.Text('Cadastrar Imóvel:', font=("Helvetica", 20))]],
                       pad=(30, 20))],
            [sg.Column(column1, pad=(30, 30))],
            [sg.Button('Voltar', pad=(30, 30), button_color=('white', 'red'), key=self.VOLTAR),
             sg.Button('Confirmar', pad=(0, 30), key=self.PROSSEGUIR)]
        ]


        self.__window = sg.Window('Cadastrar Imóvel').Layout(layout)
        button, values = self.__window.Read()
        self.close()
        if button == self.PROSSEGUIR:
            return values['titulo'], values['descricao']
        else:
            return None, None

    def close(self):
        self.__window.Close()
        self.__window = None
