#######################################################
# 
# TelaMenu.py
# Python implementation of the Class TelaMenu
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg

class TelaMenu(Tela):
    def __init__(self):
        self.__window = None

    def abrir_menu(self):
        sg.theme('TealMono')
        layout = [
            [sg.Radio('Cadastrar Imóvel', group_id="RD1" , key='C_IMOVEIS')],
            [sg.Radio('Exibir Imóvel', group_id="RD1", key='R_IMOVEIS')],
            [sg.Radio('Alterar Imóvel', group_id="RD1", key='U_IMOVEIS')],
            [sg.Radio('Excluir Imóvel', group_id="RD1", key='D_IMOVEIS')],
            [sg.Radio('Cadastrar Plataforma', group_id="RD1", key='C_PLATAFORMAS')],
            [sg.Radio('Exibir Plataforma', group_id="RD1", key='R_PLATAFORMAS')],
            [sg.Radio('Alterar Plataforma', group_id="RD1", key='U_PLATAFORMAS')],
            [sg.Radio('Excluir Plataforma', group_id="RD1", key='D_PLATAFORMAS')],
            [sg.Radio('Alterar Senha', group_id="RD1", key='U_SENHA')],
            [sg.Button('Prosseguir' , key='PROXIMO')],
            [sg.Button('Retornar', key='VOLTAR')]
        ]
        self.__window = sg.Window('Menu').Layout(layout)
        button, values = self.__window.Read()
        for key in values:
            if values[key]:
                escolha = key
                self.__window.Close()
                return button, escolha
        self.__window.Close()
        return button, None



