#######################################################
# 
# TelaExibePlataformas.py
# Python implementation of the Class TelaExibePlataformas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg

class TelaExibePlataformas(Tela):

    def __init__(self):
        self.__window = None

    def exibir_plataformas(self, plataformas):
        sg.theme('Reddit')

        dados = [[plataforma.titulo, plataforma.desc, plataforma.id] for plataforma in plataformas]

        colunas = ['Título', 'Descrição', 'ID']

        layout = [
            [sg.Text('Lista Plataformas:', font=("Helvetica", 20), pad=(30, 20))],
            [sg.Table(values=dados, headings=colunas, display_row_numbers=False,
                      auto_size_columns=False, num_rows=min(25, len(dados)), pad=(30, 30), col_widths=[15, 30, 10])],
            [sg.Button('Ok', pad=(30, 30))]
        ]

        self.__window = sg.Window('RBR Imóveis').Layout(layout)
        button, values = self.__window.Read()
        if button is None or button == 'Ok':
            self.__window.Close()
            return None
        self.__window.Close()
        return None

    def close(self):
        self.__window.Close()
        self.__window = None