#######################################################
# 
# Tela.py
# Python implementation of the Class Tela
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################


class Tela:
    pass