#######################################################
# 
# TelaAlterarPlataformas.py
# Python implementation of the Class TelaAlterarPlataformas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg

class TelaAlterarPlataformas(Tela):

    def __init__(self):
        self.__window = None

    def alterar_plataforma(self, plataforma):
        sg.theme('TealMono')
        layout = [
            [sg.Text('Título:'), sg.Input(key='titulo', default_text=plataforma.titulo)],
            [sg.Text('Descrição:'), sg.Input(key='descricao', default_text=plataforma.descricao)],
            [sg.Button('Prosseguir')],
            [sg.Button('Retornar')]
        ]