#######################################################
# 
# TelaVerificaSenha.py
# Python implementation of the Class TelaVerificaSenha
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela

import PySimpleGUI as sg

class TelaVerificaSenha(Tela):

    def __init__(self):
        self.__window = None

    def verifica_senha(self):
        sg.theme('Reddit')

        layout = [
            [sg.Column([[sg.Text('Bem-Vindo', justification='center', font=("Helvetica", 25))]],
                       justification='center')],
            [sg.Text('Chave de acesso:', font=("Helvetica", 15)), sg.Input(key='senha', password_char='*')],
            [sg.Column([[sg.Text('A chave padrão é rbr_imoveis', justification='center', font=("Helvetica", 15))]],
                       justification='center')],
            [sg.Button('Confirmar')]
        ]

        self.__window = sg.Window('RBR Imóveis', layout, finalize=True)
        self.__window['senha'].bind('<Return>', '_Enter')
        self.__window['senha'].bind('<KP_Enter>', '_Enter')
        button, values = self.__window.Read()
        if button is None:
            exit()
        else:
            self.__window.Close()
            return values['senha']