#######################################################
# 
# TelaReceitas.py
# Python implementation of the Class TelaReceitas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela
import PySimpleGUI as sg

class TelaReceitas(Tela):

    def __init__(self):
        super().__init__()
        self.init_components()



    def init_components(self):
        sg.ChangeLookAndFeel('Reddit')
        layout = [
            [sg.Text('Receitas')],
            [sg.Button('Listar Receitas', key='listar_receitas')],
            [sg.Button('Adicionar Receita', key='adicionar_receita')],
            [sg.Button('Remover Receita', key='remover_receita')],
            [sg.Button('Voltar', key='voltar')]
        ]
        self.__window = sg.Window('Receitas').Layout(layout)
