#######################################################
# 
# TelaExibeSaques.py
# Python implementation of the Class TelaExibeSaques
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:54 PM
# Original author: rlnet
# 
#######################################################
from limites.Tela import Tela

class TelaExibeSaques(Tela):
    pass