#######################################################
# 
# ControladorMenu.py
# Python implementation of the Class ControladorMenu
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaMenu import TelaMenu

class ControladorMenu:
    m_TelaMenu= TelaMenu()

    def abrir_menu(self):
        pass

    def retornar_opcao(self):
        pass