#######################################################
# 
# ControladorRelatorios.py
# Python implementation of the Class ControladorRelatorios
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaRelatorioAnual import TelaRelatorioAnual
from limites.TelaRelatorioImovel import TelaRelatorioImovel

class ControladorRelatorios:
    m_TelaRelatorioAnual= TelaRelatorioAnual()

    m_TelaRelatorioImovel= TelaRelatorioImovel()

    def relatorio_anual():
        pass

    def relatorio_imovel():
        pass