#######################################################
# 
# ControladorGeraIdAporte.py
# Python implementation of the Class ControladorGeraIdAporte
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorAporte import DAOContadorAporte

class ControladorGeraIdAporte(ControladorGeradorId):


    def __init__(self):
        self.__dao = DAOContadorAporte("./contadorAporte.pkl")

    def gera_id(self) -> int:
        return self.__dao.update()