#######################################################
# 
# ControladorSaques.py
# Python implementation of the Class ControladorSaques
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaSaques import TelaSaques
from limites.TelaCadastraSaques import TelaCadastraSaques
from limites.TelaExibeSaques import TelaExibeSaques
from limites.TelaExcluiSaques import TelaExcluiSaques
from DAOs.DAOSaque import DAOSaque
from controladores.ControladorGeraIdSaque import ControladorGeraIdSaque

class ControladorSaques:
    m_TelaSaques= TelaSaques()

    m_TelaCadastraSaques= TelaCadastraSaques()

    m_TelaExibeSaques= TelaExibeSaques()

    m_TelaExcluiSaques= TelaExcluiSaques()

    m_DAOSaque= DAOSaque()

    m_ControladorGeraIdSaque= ControladorGeraIdSaque()

    def cadastrar_saque():
        pass

    def excluir_saque():
        pass

    def exibir_saque():
        pass

    def listar_saques():
        pass

    def listar_saques_ano():
        pass