#######################################################
# 
# ControladorCaixa.py
# Python implementation of the Class ControladorCaixa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from DAOs.DAOCaixa import DAOCaixa
from limites.TelaCaixa import TelaCaixa

class ControladorCaixa:

    def __init__(self, receitas: list, despesas: list, saques: list, aportes: list):
        self.__dao_caixa = DAOCaixa("caixa.pkl")
        self.__caixa = self.__dao_caixa.read()
        self.__tela = TelaCaixa()
        self.__receitas = receitas
        self.__despesas = despesas
        self.__saques = saques
        self.__aportes = aportes

    @property
    def caixa(self):
        return self.__caixa

    @property
    def tela(self):
        return self.__tela

    @property
    def receitas(self):
        return self.__receitas

    @property
    def despesas(self):
        return self.__despesas

    @property
    def saques(self):
        return self.__saques

    @property
    def aportes(self):
        return self.__aportes


    def atualizar_caixa():
        total = 0
        for despesa in despesas:
            total -= despesa.valor
        for receita in receitas:
            total += receita.valor
        for aporte in aportes:
            total += aporte.valor
        for saque in saques:
            total -= saque.valor
        self.__dao_caixa.update(total)

    def exibir_caixa(self):
        self.__tela.exibir_caixa()



