#######################################################
# 
# ControladorMenu.py
# Python implementation of the Class ControladorMenu
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaMenu import TelaMenu
from limites.TelaPopup import TelaPopup
import PySimpleGUI as sg

class ControladorMenu:

    IMOVEIS = "IMOVEIS"
    PLATAFORMAS = "PLATAFORMAS"
    C_IMOVEIS = "C_IMOVEIS"
    R_IMOVEIS = "R_IMOVEIS"
    U_IMOVEIS = "U_IMOVEIS"
    D_IMOVEIS = "D_IMOVEIS"
    C_PLATAFORMAS = "C_PLATAFORMAS"
    R_PLATAFORMAS = "R_PLATAFORMAS"
    U_PLATAFORMAS = "U_PLATAFORMAS"
    D_PLATAFORMAS = "D_PLATAFORMAS"
    U_SENHA = "U_SENHA"
    PROXIMO = "PROXIMO"
    VOLTAR = "VOLTAR"
    SAIR = "SAIR"



    def __init__(self):
        self.__tela = TelaMenu()
        self.__tela_popup = TelaPopup()


    def abrir_menu(self):

        match self.__tela.abrir_menu():
            case ControladorMenu.PROXIMO, ControladorMenu.IMOVEIS:
                self.__tela_popup.mostra_popup("Aqui vai aparecer o menu de imóveis")

            case ControladorMenu.PROXIMO, ControladorMenu.PLATAFORMAS:
                self.__tela_popup.mostra_popup("Aqui vai aparecer o menu de plataformas")

            case ControladorMenu.PROXIMO, ControladorMenu.U_SENHA:
                return ControladorMenu.U_SENHA
            case ControladorMenu.SAIR:
                return ControladorMenu.SAIR
            case _:
                pass
