#######################################################
# 
# ControladorSaques.py
# Python implementation of the Class ControladorSaques
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaSaques import TelaSaques
from limites.TelaCadastraSaques import TelaCadastraSaques
from limites.TelaExibeSaques import TelaExibeSaques
from limites.TelaExcluiSaques import TelaExcluiSaques
from limites.TelaPopup import TelaPopup
from DAOs.DAOSaque import DAOSaque
from controladores.ControladorGeraIdSaque import ControladorGeraIdSaque

class ControladorSaques:


    def cadastrar_saque(self):
        pass

    def excluir_saque(self):
        pass

    def exibir_saque(self):
        pass

    def listar_saques(self):
        pass

    def listar_saques_ano(self):
        pass