#######################################################
# 
# ControladorGeraIdPlataforma.py
# Python implementation of the Class ControladorGeraIdPlataforma
# Generated by Enterprise Architect
# Created on:      16-Apr-2024 3:14:54 AM
# Original author: rlnet
# 
#######################################################
from DAOs.DAOContadorPlataforma import DAOContadorPlataforma
from controladores.ControladorGeradorId import ControladorGeradorId

class ControladorGeraIdPlataforma(ControladorGeradorId):
    m_DAOContadorPlataforma= DAOContadorPlataforma()

    def gera_id(self):
        pass