#######################################################
# 
# ControladorDespesas.py
# Python implementation of the Class ControladorDespesas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaDespesas import TelaDespesas
from limites.TelaCadastraDespesas import TelaCadastraDespesas
from limites.TelaExibeDespesas import TelaExibeDespesas
from limites.TelaExcluiDespesas import TelaExcluiDespesas
from limites.TelaPopup import TelaPopup
from DAOs.DAODespesa import DAODespesa
from controladores.ControladorGeraIdDespesa import ControladorGeraIdDespesa

class ControladorDespesas:


    def cadastrar_despesa(self):
        pass

    def excluir_despesa(self):
        pass

    def exibir_despesa(self):
        pass

    def find_despesa(self):
        pass

    def listar_despesas_ano(self):
        pass

    def listar_despesas_imovel(self):
        pass