#######################################################
# 
# ControladorSenha.py
# Python implementation of the Class ControladorSenha
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaVerificaSenha import TelaVerificaSenha
from limites.TelaAlteraSenha import TelaAlteraSenha
from DAOs.DAOSenha import DAOSenha

class ControladorSenha:


    def alterar_senha(self):
        pass

    def verificar_senha(self):
        pass