#######################################################
# 
# ControladorAportes.py
# Python implementation of the Class ControladorAportes
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaAportes import TelaAportes
from limites.TelaCadastraAportes import TelaCadastraAportes
from limites.TelaExibeAportes import TelaExibeAportes
from limites.TelaExcluiAportes import TelaExcluiAportes
from DAOs.DAOAporte import DAOAporte
from controladores.ControladorGeraIdAporte import ControladorGeraIdAporte

class ControladorAportes:
    m_TelaAportes= TelaAportes()

    m_TelaCadastraAportes= TelaCadastraAportes()

    m_TelaExibeAportes= TelaExibeAportes()

    m_TelaExcluiAportes= TelaExcluiAportes()

    m_DAOAporte= DAOAporte()

    m_ControladorGeraIdAporte= ControladorGeraIdAporte()

    def cadastrar_aporte():
        pass

    def excluir_aporte():
        pass

    def exibir_aporte():
        pass

    def find_aporte():
        pass

    def listar_aportes():
        pass

    def listar_aportes_ano():
        pass