#######################################################
# 
# ControladorMenu.py
# Python implementation of the Class ControladorMenu
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaMenu import TelaMenu
import PySimpleGUI as sg

class ControladorMenu:

    IMOVEIS = "IMOVEIS"
    PLATAFORMAS = "PLATAFORMAS"
    U_SENHA = "U_SENHA"
    PROSSEGUIR = "PROSSEGUIR"
    VOLTAR = "VOLTAR"
    SAIR = "SAIR"
    CAIXA = "CAIXA"



    def __init__(self):
        self.__tela = TelaMenu()


    def abrir_menu(self):

        match self.__tela.abrir_menu():
            case self.IMOVEIS:
                return self.IMOVEIS
            case self.PLATAFORMAS:
                return self.PLATAFORMAS
            case self.CAIXA:
                return self.CAIXA
            case self.U_SENHA:
                return self.U_SENHA
            case self.PROSSEGUIR:
                return self.PROSSEGUIR
            case self.SAIR:
                return self.SAIR

