#######################################################
# 
# ControladorPlataformas.py
# Python implementation of the Class ControladorPlataformas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaPlataformas import TelaPlataformas
from controladores.ControladorGeraIdPlataforma import ControladorGeraIdPlataforma
from DAOs.DAOPlataforma import DAOPlataforma
from entidades.Plataforma import Plataforma


class ControladorPlataformas:
    C_PLATAFORMAS = "C_PLATAFORMAS"
    R_PLATAFORMAS = "R_PLATAFORMAS"
    U_PLATAFORMAS = "U_PLATAFORMAS"
    D_PLATAFORMAS = "D_PLATAFORMAS"
    EXCLUIR = "Excluir"
    PROSSEGUIR = "PROSSEGUIR"
    PROXIMO = "PROXIMO"
    VOLTAR = "VOLTAR"

    def __init__(self):
        self.__dao = DAOPlataforma("plataformas.pkl")
        self.__tela = TelaPlataformas()

    def abrir_menu(self):
        while True:
            match self.__tela.abrir_menu():
                case self.C_PLATAFORMAS:
                    self.cadastrar_plataforma()
                case self.R_PLATAFORMAS:
                    self.listar_plataformas()
                case self.U_PLATAFORMAS:
                    self.alterar_plataforma()
                case self.D_PLATAFORMAS:
                    self.excluir_plataforma()
                case self.VOLTAR:
                    return
                case None:
                    return

    def alterar_plataforma(self):
        nova_plataforma = list()
        nova_plataforma_id, action = self.__tela.selecionar_plataforma(self.__dao.read())
        if nova_plataforma_id is None or action is None:
            if action == self.PROSSEGUIR:
                self.__tela.mostra_popup("Erro: Selecione uma plataforma.")
            return
        elif action == self.PROSSEGUIR:
            plataforma_atual = self.find_plataforma_por_id(nova_plataforma_id)
            resultado = self.__tela.alterar_plataforma(plataforma_atual)
            if len(resultado) == 0:
                return
            else:
                nova_plataforma.append(resultado[0])
                nova_plataforma.append(resultado[1])
                new_action = resultado[2]
            if new_action != self.PROSSEGUIR:
                return
            elif nova_plataforma[0] is None or nova_plataforma[1] is None:
                self.__tela.mostra_popup("Erro: O título e a descrição da plataforma não podem estar vazios.")
                return
            else:
                sucesso = self.__dao.update(id=nova_plataforma_id, novo_titulo=nova_plataforma[0],
                                            nova_desc=nova_plataforma[1])
                if sucesso:
                    self.__tela.mostra_popup("Plataforma alterada com sucesso.")
                    return
                else:
                    self.__tela.mostra_popup("Erro: Não foi possível alterar a plataforma.")
                    return


    def cadastrar_plataforma(self):
        titulo, desc, action = self.__tela.cadastrar_plataforma()
        if titulo is None or desc is None:
            if action == self.PROSSEGUIR:
                self.__tela.mostra_popup("Erro: O título e a descrição da plataforma não podem estar vazios.")
            return
        else:
            self.__dao.create(desc=desc, titulo=titulo, id=ControladorGeraIdPlataforma().gera_id())
            self.__tela.mostra_popup("Plataforma cadastrada com sucesso.")
            return

    def excluir_plataforma(self):
        id_plataforma, action = self.__tela.excluir_plataforma(self.__dao.read())
        if id_plataforma is None:
            if action == self.EXCLUIR:
                self.__tela.mostra_popup("Erro: O ID da plataforma não pode estar vazio.")
            return
        else:
            self.__dao.delete(id=id_plataforma)
            self.__tela.mostra_popup("Plataforma excluída com sucesso.")
            return

    def find_plataforma(self, nome_plataforma: str) -> list[Plataforma]:
        return [plataforma for plataforma in self.__dao.read() if plataforma.nome == nome_plataforma][0]

    def listar_plataformas(self):
        self.__tela.exibir_plataformas(self.__dao.read())

    def pegar_todas_plataformas(self) -> list[Plataforma]:
        plataformas = [plataforma for plataforma in self.__dao.read()]
        return plataformas

    def find_plataforma_por_id(self, id_plataforma: int) -> Plataforma:
        encontrados = [plataforma for plataforma in self.__dao.read() if plataforma.id == id_plataforma]
        return encontrados[0] if len(encontrados) > 0 else None

