#######################################################
# 
# ControladorPlataformas.py
# Python implementation of the Class ControladorPlataformas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaPlataformas import TelaPlataformas
from limites.TelaAlterarPlataformas import TelaAlterarPlataformas
from limites.TelaExcluiPlataformas import TelaExcluiPlataformas
from limites.TelaExibePlataformas import TelaExibePlataformas
from limites.TelaCadastraPlataformas import TelaCadastraPlataformas
from DAOs.DAOPlataforma import DAOPlataforma

class ControladorPlataformas:


    def alterar_plataforma(self):
        pass

    def cadastrar_plataforma(self):
        pass

    def excluir_plataforma(self):
        pass

    def exibir_plataforma(self):
        pass

    def find_plataforma(self):
        pass

    def listar_plataformas(self):
        pass