#######################################################
# 
# ControladorGeraIdReceita.py
# Python implementation of the Class ControladorGeraIdReceita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorReceita import DAOContadorReceita


class ControladorGeraIdReceita(ControladorGeradorId):

    def __init__(self):
        self.__dao = DAOContadorReceita("contador_receita.pkl")

    @property
    def dao(self):
        return self.__dao

    def gera_id(self) -> int:
        return self.dao.update()
