#######################################################
# 
# ControladorDespesas.py
# Python implementation of the Class ControladorDespesas
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaDespesas import TelaDespesas
from limites.TelaDespesas import TelaDespesas
# from limites.TelaPopup import TelaPopup 
from DAOs.DAODespesa import DAODespesa
from controladores.ControladorGeraIdDespesa import ControladorGeraIdDespesa

class ControladorDespesas:
    C_DESPESAS = "C_DESPESAS"
    R_DESPESAS = "R_DESPESAS"
    D_DESPESAS = "D_DESPESAS"
    PROXIMO = "PROXIMO"
    VOLTAR = "VOLTAR"

    def __init__(self):
        self.__dao = DAODespesa("despesas.pkl")
        self.__tela = TelaDespesas()

    def abrir_menu(self):
        while True:
            match self.__tela.abrir_menu():
                case self.C_DESPESAS:
                    self.cadastrar_despesa()
                case self.R_DESPESAS:
                    self.listar_despesas()
                case self.D_DESPESAS:
                    self.exclui_despesa()
                case self.VOLTAR:
                    return
                case None:
                    return


    def cadastrar_despesa(self):
        pass

    def excluir_despesa(self):
        pass

    def exibir_despesa(self):
        pass

    def find_despesa(self):
        pass

    def listar_despesas_ano(self):
        pass

    def listar_despesas_imovel(self):
        pass