#######################################################
# 
# ControladorGeraIdDespesa.py
# Python implementation of the Class ControladorGeraIdDespesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorDespesa import DAOContadorDespesa

class ControladorGeraIdDespesa(ControladorGeradorId):
    m_DAOContadorDespesa= DAOContadorDespesa()

    def gera_id(self):
        pass