#######################################################
# 
# ControladorSistema.py
# Python implementation of the Class ControladorSistema
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorReceitas import ControladorReceitas
from controladores.ControladorMenu import ControladorMenu
from controladores.ControladorSenha import ControladorSenha
from controladores.ControladorDespesas import ControladorDespesas
from controladores.ControladorSaques import ControladorSaques
from controladores.ControladorAportes import ControladorAportes
from controladores.ControladorRelatorios import ControladorRelatorios
from controladores.ControladorPlataformas import ControladorPlataformas
from controladores.ControladorImoveis import ControladorImoveis
from controladores.ControladorCaixa import ControladorCaixa

class ControladorSistema:

    def __init__(self):
        self.__autenticado = False
        self.__ControladorReceitas= ControladorReceitas()
        self.__ControladorMenu= ControladorMenu()
        self.__ControladorSenha= ControladorSenha()
        self.__ControladorDespesas= ControladorDespesas()
        self.__ControladorSaques= ControladorSaques()
        self.__ControladorAportes= ControladorAportes()
        self.__ControladorRelatorios= ControladorRelatorios()
        self.__ControladorPlataformas= ControladorPlataformas()
        self.__ControladorImoveis= ControladorImoveis()
        self.__ControladorCaixa= ControladorCaixa()

    def inicializar(self):
        while not self.__autenticado:
            self.__ControladorSenha.verificar_senha()
        self.__ControladorMenu.abrir_menu()

    def processar_operacao(self):
        pass