#######################################################
# 
# ControladorGeradorId.py
# Python implementation of the Class ControladorGeradorId
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################

from abc import ABC, abstractmethod
class ControladorGeradorId(ABC):
    @abstractmethod
    def gera_id(self):
        pass