#######################################################
# 
# ControladorGeraIdReceita.py
# Python implementation of the Class ControladorGeraIdReceita
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorReceita import DAOContadorReceita

class ControladorGeraIdReceita(ControladorGeradorId):
    m_DAOContadorReceita= DAOContadorReceita()

    def gera_id(self):
        pass