#######################################################
# 
# ControladorSistema.py
# Python implementation of the Class ControladorSistema
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorReceitas import ControladorReceitas
from controladores.ControladorMenu import ControladorMenu
from controladores.ControladorSenha import ControladorSenha
from controladores.ControladorDespesas import ControladorDespesas
from controladores.ControladorSaques import ControladorSaques
from controladores.ControladorAportes import ControladorAportes
from controladores.ControladorRelatorios import ControladorRelatorios
from controladores.ControladorPlataformas import ControladorPlataformas
from controladores.ControladorImoveis import ControladorImoveis
from controladores.ControladorCaixa import ControladorCaixa

class ControladorSistema:
    __autenticado = False
    m_ControladorReceitas= ControladorReceitas()

    m_ControladorMenu= ControladorMenu()

    m_ControladorSenha= ControladorSenha()

    m_ControladorDespesas= ControladorDespesas()

    m_ControladorSaques= ControladorSaques()

    m_ControladorAportes= ControladorAportes()

    m_ControladorRelatorios= ControladorRelatorios()

    m_ControladorPlataformas= ControladorPlataformas()

    m_ControladorImoveis= ControladorImoveis()

    m_ControladorCaixa= ControladorCaixa()

    def inicializar(self):
        pass

    def processar_operacao(self):
        pass