#######################################################
# 
# ControladorRelatorios.py
# Python implementation of the Class ControladorRelatorios
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaRelatorioAnual import TelaRelatorioAnual
from limites.TelaRelatorioImovel import TelaRelatorioImovel
from collections import Counter

class ControladorRelatorios:
    def __init__(self):
        self.__tela = TelaRelatorioImovel()

    def exibir_relatorio_imovel(self, controlador_imovel, controlador_despesa, controlador_receita, controlador_saque, controlador_aporte):
        imoveis = controlador_imovel.pegar_todos_imoveis()

        if not controlador_imovel.validar_existencia_imoveis(imoveis):
            return
        
        imovel_selecionado = self.__tela.selecionar_imovel(imoveis)
        
        if imovel_selecionado is None:
            return
        
        despesas = controlador_despesa.pegar_despesas_por_imovel(imovel_selecionado.id)
        receitas = controlador_receita.pegar_receitas_por_imovel(imovel_selecionado.id)

        total_despesas = sum(float(despesa.valor) for despesa in despesas)

        total_receitas = sum(float(receita.valor) for receita in receitas)

        # Tags mais utilizadas
        contador_tags = Counter()
        for despesa in despesas:
            contador_tags.update(despesa.tags)
        
        for receita in receitas:
            contador_tags.update(receita.tags)
        
        if contador_tags:
            max_ocorrencias = max(contador_tags.values())
            tags_mais_utilizadas = [(tag, count) for tag, count in contador_tags.items() if count == max_ocorrencias]
        else:
            tags_mais_utilizadas = []

        # Pataforma mais utilizada
        contador_plataformas = Counter(receita.plataforma.titulo for receita in receitas)
        if contador_plataformas:
            max_ocorrencias_plataformas = max(contador_plataformas.values())
            plataforma_mais_utilizada = [(plataforma, count) for plataforma, count in contador_plataformas.items() if count == max_ocorrencias_plataformas]
        else:
            plataforma_mais_utilizada = []

        self.__tela.exibir_relatorio(imovel_selecionado, despesas, receitas, total_despesas, total_receitas, tags_mais_utilizadas, plataforma_mais_utilizada)
