#######################################################
# 
# ControladorGeraIdDespesa.py
# Python implementation of the Class ControladorGeraIdDespesa
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorDespesa import DAOContadorDespesa

class ControladorGeraIdDespesa(ControladorGeradorId):

    def __init__(self):
        self.__dao = DAOContadorDespesa("./contadorDespesa.pkl")

    def gera_id(self) -> int:
        return self.__dao.update()