#######################################################
# 
# ControladorGeraIdSaque.py
# Python implementation of the Class ControladorGeraIdSaque
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorSaque import DAOContadorSaque

class ControladorGeraIdSaque(ControladorGeradorId):

    def __init__(self):
        self.__dao = DAOContadorSaque("./contadorSaque.pkl")

    def gera_id(self) -> int:
        return self.__dao.update()