#######################################################
# 
# ControladorImoveis.py
# Python implementation of the Class ControladorImoveis
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from limites.TelaImoveis import TelaImoveis
from limites.TelaAlterarImoveis import TelaAlterarImoveis
from limites.TelaExcluiImoveis import TelaExcluiImoveis
from limites.TelaExibeImoveis import TelaExibeImoveis
from limites.TelaCadastraImoveis import TelaCadastraImoveis
from DAOs.DAOImovel import DAOImovel

class ControladorImoveis:
    m_TelaImoveis= TelaImoveis()

    m_TelaAlterarImoveis= TelaAlterarImoveis()

    m_TelaExcluiImoveis= TelaExcluiImoveis()

    m_TelaExibeImoveis= TelaExibeImoveis()

    m_TelaCadastraImoveis= TelaCadastraImoveis()

    m_DAOImovel= DAOImovel()

    def alterar_imovel(self):
        pass

    def cadastrar_imovel(self):
        pass

    def excluir_imovel(self):
        pass

    def exibir_imovel(self):
        pass

    def find_imovel(self):
        pass

    def listar_imoveis(self):
        pass