#######################################################
# 
# ControladorGeraIdImovel.py
# Python implementation of the Class ControladorGeraIdImovel
# Generated by Enterprise Architect
# Created on:      15-Apr-2024 9:30:53 PM
# Original author: rlnet
# 
#######################################################
from controladores.ControladorGeradorId import ControladorGeradorId
from DAOs.DAOContadorImovel import DAOContadorImovel

class ControladorGeraIdImovel(ControladorGeradorId):
    m_DAOContadorImovel= DAOContadorImovel()

    def gera_id():
        pass